"use client";

import { useState } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Loader2, Copy, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { generateJobDescription } from "@/ai/flows/generate-job-description";
import { Skeleton } from "@/components/ui/skeleton";

export function JobDescriptionForm() {
  const [input, setInput] = useState("");
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const handleCopy = () => {
    navigator.clipboard.writeText(description);
    setCopied(true);
    toast({
      title: "Copied!",
      description: "Job description copied to clipboard.",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) {
      toast({
        title: "Input required",
        description: "Please describe the job you want to post.",
        variant: "destructive",
      });
      return;
    }
    setLoading(true);
    setDescription("");
    try {
      const result = await generateJobDescription(input);
      setDescription(result);
    } catch (error) {
      console.error(error);
      toast({
        title: "Error",
        description: "Failed to generate job description. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card>
      <form onSubmit={handleSubmit}>
        <CardHeader>
          <CardTitle>Job Details</CardTitle>
          <CardDescription>Enter a short summary of the role, including key responsibilities and required skills.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid w-full items-center gap-4">
            <div className="flex flex-col space-y-1.5">
              <Label htmlFor="job-description-input">Job Summary</Label>
              <Textarea
                id="job-description-input"
                placeholder="e.g., 'A senior frontend engineer with React and TypeScript experience for a fast-growing fintech startup.'"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                rows={4}
                disabled={loading}
              />
            </div>
          </div>
        </CardContent>
        <CardFooter className="flex justify-end">
          <Button type="submit" disabled={loading}>
            {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Generate Description
          </Button>
        </CardFooter>
      </form>
      
      {(loading || description) && (
        <>
          <div className="mx-6"><div className="w-full h-px bg-border"></div></div>
          <CardHeader>
            <CardTitle>Generated Description</CardTitle>
            <CardDescription>Here is the job description generated by our AI. You can copy it or use it to create a new opportunity post.</CardDescription>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="space-y-4">
                <Skeleton className="h-4 w-1/4" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-3/4" />
                <Skeleton className="h-4 w-1/4" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-2/3" />
              </div>
            ) : (
              <div className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap rounded-md border bg-secondary/50 p-4 font-sans">
                {description}
              </div>
            )}
          </CardContent>
          {!loading && description && (
            <CardFooter className="flex justify-end gap-2">
              <Button variant="outline" onClick={handleCopy}>
                {copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
                {copied ? "Copied" : "Copy Text"}
              </Button>
              <Button>Use Description</Button>
            </CardFooter>
          )}
        </>
      )}
    </Card>
  );
}
